export const EXAMPLE_WELCOME = 'ADD_TO_CART'
export const LOGIN_COMMITTING = 'LOGIN_COMMITTING'
export const LOGIN_COMMITTED = 'LOGIN_COMMITTED'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const FORGET_COMMITTING = 'FORGET_COMMITTING'
export const FORGET_COMMITTED = 'FORGET_COMMITTED'
export const FORGET_FAILURE = 'FORGET_FAILURE'

export const REGISTER_COMMITTING = 'REGISTER_COMMITTING'
export const REGISTER_COMMITTED = 'REGISTER_COMMITTED'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
