// location change
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

// header 部分的快捷方式
export const SHORTCUT_INITING = 'SHORTCUT_INITING'
export const SHORTCUT_INITED = 'SHORTCUT_INITED'
export const SHORTCUT_FAILURE = 'SHORTCUT_FAILURE'

// header 部分的用户信息获取方式
export const LOGIN_INFO_INITING = 'LOGIN_INFO_INITING'
export const LOGIN_INFO_INITED = 'LOGIN_INFO_INITED'
export const LOGIN_INFO_FAILURE = 'LOGIN_INFO_FAILURE'


// leftMenu 可用目录获取
export const LEFT_MENU_INITING = 'LEFT_MENU_INITING'
export const LEFT_MENU_INITED = 'LEFT_MENU_INITED'
export const LEFT_MENU_FAILURE = 'LEFT_MENU_FAILURE'


// 首页数据获取
export const INDEX_DATA_INITING = 'INDEX_DATA_INITING'
export const INDEX_DATA_INITED = 'INDEX_DATA_INITED'
export const INDEX_DATA_FAILURE = 'INDEX_DATA_FAILURE'

// options
export const ACCESSCONTROL_POST_OPTIONS_GOT = 'ACCESSCONTROL_POST_OPTIONS_GOT'
export const ACCESSCONTROL_AUTHORITYPARENT_OPTIONS_GOT = 'ACCESSCONTROL_AUTHORITYPARENT_OPTIONS_GOT'
export const ACCESSCONTROL_AUTHORITYPARENT_TREE_OPTIONS_GOT = 'ACCESSCONTROL_AUTHORITYPARENT_TREE_OPTIONS_GOT'
export const ACCESSCONTROL_ROLE_OPTIONS_GOT = 'ACCESSCONTROL_ROLE_OPTIONS_GOT'

export const BASEDATA_PRODUCTCATEGORY_PARENT_OPTIONS_GOT = 'BASEDATA_PRODUCTCATEGORY_PARENT_OPTIONS_GOT'
export const BASEDATA_PRODUCTCATEGORY_PARENT_TREE_OPTIONS_GOT = 'BASEDATA_PRODUCTCATEGORY_PARENT_TREE_OPTIONS_GOT'

export const BASEDATA_STORE_OPTIONS_GOT = 'BASEDATA_STORE_OPTIONS_GOT'

export const BASEDATA_EMPLOYEE_OPTIONS_GOT = 'BASEDATA_EMPLOYEE_OPTIONS_GOT'

export const BASEDATA_SUPPLIER_OPTIONS_GOT = 'BASEDATA_SUPPLIER_OPTIONS_GOT'

// 访问控制 ---
// 职位管理 ---
export const ACCESSCONTROL_POST_LIST_QUERY = 'ACCESSCONTROL_POST_LIST_QUERY'
export const ACCESSCONTROL_POST_LIST_GOT = 'ACCESSCONTROL_POST_LIST_GOT'
export const ACCESSCONTROL_POST_LIST_FAILURE = 'ACCESSCONTROL_POST_LIST_FAILURE'

export const ACCESSCONTROL_POST_SINGLE_INIT = 'ACCESSCONTROL_POST_SINGLE_INIT'

export const ACCESSCONTROL_POST_SINGLE_QUERY = 'ACCESSCONTROL_POST_SINGLE_QUERY'
export const ACCESSCONTROL_POST_SINGLE_GOT = 'ACCESSCONTROL_POST_SINGLE_GOT'
export const ACCESSCONTROL_POST_SINGLE_FAILURE = 'ACCESSCONTROL_POST_SINGLE_FAILURE'

export const ACCESSCONTROL_POST_SAVE_BEGIN = 'ACCESSCONTROL_POST_SAVE_BEGIN'
export const ACCESSCONTROL_POST_SAVE_SUCCESS = 'ACCESSCONTROL_POST_SAVE_SUCCESS'
export const ACCESSCONTROL_POST_SAVE_FAILURE = 'ACCESSCONTROL_POST_SAVE_FAILURE'


export const ACCESSCONTROL_POST_DELETE_BEGIN = 'ACCESSCONTROL_POST_DELETE_BEGIN'
export const ACCESSCONTROL_POST_DELETE_SUCCESS = 'ACCESSCONTROL_POST_DELETE_SUCCESS'
export const ACCESSCONTROL_POST_DELETE_FAILURE = 'ACCESSCONTROL_POST_DELETE_FAILURE'

// 权限管理 ---
export const ACCESSCONTROL_AUTHORITY_LIST_QUERY = 'ACCESSCONTROL_AUTHORITY_LIST_QUERY'
export const ACCESSCONTROL_AUTHORITY_LIST_GOT = 'ACCESSCONTROL_AUTHORITY_LIST_GOT'
export const ACCESSCONTROL_AUTHORITY_LIST_FAILURE = 'ACCESSCONTROL_AUTHORITY_LIST_FAILURE'

export const ACCESSCONTROL_AUTHORITY_SINGLE_INIT = 'ACCESSCONTROL_AUTHORITY_SINGLE_INIT'

export const ACCESSCONTROL_AUTHORITY_SINGLE_QUERY = 'ACCESSCONTROL_AUTHORITY_SINGLE_QUERY'
export const ACCESSCONTROL_AUTHORITY_SINGLE_GOT = 'ACCESSCONTROL_AUTHORITY_SINGLE_GOT'
export const ACCESSCONTROL_AUTHORITY_SINGLE_FAILURE = 'ACCESSCONTROL_AUTHORITY_SINGLE_FAILURE'

export const ACCESSCONTROL_AUTHORITY_SAVE_BEGIN = 'ACCESSCONTROL_AUTHORITY_SAVE_BEGIN'
export const ACCESSCONTROL_AUTHORITY_SAVE_SUCCESS = 'ACCESSCONTROL_AUTHORITY_SAVE_SUCCESS'
export const ACCESSCONTROL_AUTHORITY_SAVE_FAILURE = 'ACCESSCONTROL_AUTHORITY_SAVE_FAILURE'

export const ACCESSCONTROL_AUTHORITY_DELETE_BEGIN = 'ACCESSCONTROL_AUTHORITY_DELETE_BEGIN'
export const ACCESSCONTROL_AUTHORITY_DELETE_SUCCESS = 'ACCESSCONTROL_AUTHORITY_DELETE_SUCCESS'
export const ACCESSCONTROL_AUTHORITY_DELETE_FAILURE = 'ACCESSCONTROL_AUTHORITY_DELETE_FAILURE'

// 角色管理 ---
export const ACCESSCONTROL_ROLE_LIST_QUERY = 'ACCESSCONTROL_ROLE_LIST_QUERY'
export const ACCESSCONTROL_ROLE_LIST_GOT = 'ACCESSCONTROL_ROLE_LIST_GOT'
export const ACCESSCONTROL_ROLE_LIST_FAILURE = 'ACCESSCONTROL_ROLE_LIST_FAILURE'

export const ACCESSCONTROL_ROLE_SINGLE_INIT = 'ACCESSCONTROL_ROLE_SINGLE_INIT'

export const ACCESSCONTROL_ROLE_SINGLE_QUERY = 'ACCESSCONTROL_ROLE_SINGLE_QUERY'
export const ACCESSCONTROL_ROLE_SINGLE_GOT = 'ACCESSCONTROL_ROLE_SINGLE_GOT'
export const ACCESSCONTROL_ROLE_SINGLE_FAILURE = 'ACCESSCONTROL_ROLE_SINGLE_FAILURE'

export const ACCESSCONTROL_ROLE_SAVE_BEGIN = 'ACCESSCONTROL_ROLE_SAVE_BEGIN'
export const ACCESSCONTROL_ROLE_SAVE_SUCCESS = 'ACCESSCONTROL_ROLE_SAVE_SUCCESS'
export const ACCESSCONTROL_ROLE_SAVE_FAILURE = 'ACCESSCONTROL_ROLE_SAVE_FAILURE'


export const ACCESSCONTROL_ROLE_DELETE_BEGIN = 'ACCESSCONTROL_ROLE_DELETE_BEGIN'
export const ACCESSCONTROL_ROLE_DELETE_SUCCESS = 'ACCESSCONTROL_ROLE_DELETE_SUCCESS'
export const ACCESSCONTROL_ROLE_DELETE_FAILURE = 'ACCESSCONTROL_ROLE_DELETE_FAILURE'


// 用户管理 ---
export const ACCESSCONTROL_USER_LIST_QUERY = 'ACCESSCONTROL_USER_LIST_QUERY'
export const ACCESSCONTROL_USER_LIST_GOT = 'ACCESSCONTROL_USER_LIST_GOT'
export const ACCESSCONTROL_USER_LIST_FAILURE = 'ACCESSCONTROL_USER_LIST_FAILURE'

export const ACCESSCONTROL_USER_SINGLE_INIT = 'ACCESSCONTROL_USER_SINGLE_INIT'

export const ACCESSCONTROL_USER_SINGLE_QUERY = 'ACCESSCONTROL_USER_SINGLE_QUERY'
export const ACCESSCONTROL_USER_SINGLE_GOT = 'ACCESSCONTROL_USER_SINGLE_GOT'
export const ACCESSCONTROL_USER_SINGLE_FAILURE = 'ACCESSCONTROL_USER_SINGLE_FAILURE'

export const ACCESSCONTROL_USER_SAVE_BEGIN = 'ACCESSCONTROL_USER_SAVE_BEGIN'
export const ACCESSCONTROL_USER_SAVE_SUCCESS = 'ACCESSCONTROL_USER_SAVE_SUCCESS'
export const ACCESSCONTROL_USER_SAVE_FAILURE = 'ACCESSCONTROL_USER_SAVE_FAILURE'


export const ACCESSCONTROL_USER_DELETE_BEGIN = 'ACCESSCONTROL_USER_DELETE_BEGIN'
export const ACCESSCONTROL_USER_DELETE_SUCCESS = 'ACCESSCONTROL_USER_DELETE_SUCCESS'
export const ACCESSCONTROL_USER_DELETE_FAILURE = 'ACCESSCONTROL_USER_DELETE_FAILURE'

// system info

//SystemSetting
export const SYSTEMINFO_SETTING_SINGLE_QUERY = 'SYSTEMINFO_SETTING_SINGLE_QUERY'
export const SYSTEMINFO_SETTING_SINGLE_GOT = 'SYSTEMINFO_SETTING_SINGLE_GOT'
export const SYSTEMINFO_SETTING_SINGLE_FAILURE = 'SYSTEMINFO_SETTING_SINGLE_FAILURE'

export const SYSTEMINFO_SETTING_SAVE_BEGIN = 'SYSTEMINFO_SETTING_SAVE_BEGIN'
export const SYSTEMINFO_SETTING_SAVE_SUCCESS = 'SYSTEMINFO_SETTING_SAVE_SUCCESS'
export const SYSTEMINFO_SETTING_SAVE_FAILURE = 'SYSTEMINFO_SETTING_SAVE_FAILURE'

//CompanyInfo
export const SYSTEMINFO_COMPANYINFO_SINGLE_QUERY = 'SYSTEMINFO_COMPANYINFO_SINGLE_QUERY'
export const SYSTEMINFO_COMPANYINFO_SINGLE_GOT = 'SYSTEMINFO_COMPANYINFO_SINGLE_GOT'
export const SYSTEMINFO_COMPANYINFO_SINGLE_FAILURE = 'SYSTEMINFO_COMPANYINFO_SINGLE_FAILURE'

export const SYSTEMINFO_COMPANYINFO_SAVE_BEGIN = 'SYSTEMINFO_COMPANYINFO_SAVE_BEGIN'
export const SYSTEMINFO_COMPANYINFO_SAVE_SUCCESS = 'SYSTEMINFO_COMPANYINFO_SAVE_SUCCESS'
export const SYSTEMINFO_COMPANYINFO_SAVE_FAILURE = 'SYSTEMINFO_COMPANYINFO_SAVE_FAILURE'

//Database
export const SYSTEMINFO_DATABASE_LIST_QUERY = 'SYSTEMINFO_DATABASE_LIST_QUERY'
export const SYSTEMINFO_DATABASE_LIST_GOT = 'SYSTEMINFO_DATABASE_LIST_GOT'
export const SYSTEMINFO_DATABASE_LIST_FAILURE = 'SYSTEMINFO_DATABASE_LIST_FAILURE'

export const SYSTEMINFO_DATABASE_BACKUP_BEGIN = 'SYSTEMINFO_DATABASE_BACKUP_BEGIN'
export const SYSTEMINFO_DATABASE_BACKUP_SUCCESS = 'SYSTEMINFO_DATABASE_BACKUP_SUCCESS'
export const SYSTEMINFO_DATABASE_BACKUP_FAILURE = 'SYSTEMINFO_DATABASE_BACKUP_FAILURE'

export const SYSTEMINFO_DATABASE_RESTORE_BEGIN = 'SYSTEMINFO_DATABASE_RESTORE_BEGIN'
export const SYSTEMINFO_DATABASE_RESTORE_SUCCESS = 'SYSTEMINFO_DATABASE_RESTORE_SUCCESS'
export const SYSTEMINFO_DATABASE_RESTORE_FAILURE = 'SYSTEMINFO_DATABASE_RESTORE_FAILURE'


// saleStrategy ---
export const SYSTEMINFO_SALESTRATEGY_LIST_QUERY = 'SYSTEMINFO_SALESTRATEGY_LIST_QUERY'
export const SYSTEMINFO_SALESTRATEGY_LIST_GOT = 'SYSTEMINFO_SALESTRATEGY_LIST_GOT'
export const SYSTEMINFO_SALESTRATEGY_LIST_FAILURE = 'SYSTEMINFO_SALESTRATEGY_LIST_FAILURE'

export const SYSTEMINFO_SALESTRATEGY_SINGLE_INIT = 'SYSTEMINFO_SALESTRATEGY_SINGLE_INIT'

export const SYSTEMINFO_SALESTRATEGY_SINGLE_QUERY = 'SYSTEMINFO_SALESTRATEGY_SINGLE_QUERY'
export const SYSTEMINFO_SALESTRATEGY_SINGLE_GOT = 'SYSTEMINFO_SALESTRATEGY_SINGLE_GOT'
export const SYSTEMINFO_SALESTRATEGY_SINGLE_FAILURE = 'SYSTEMINFO_SALESTRATEGY_SINGLE_FAILURE'

export const SYSTEMINFO_SALESTRATEGY_SAVE_BEGIN = 'SYSTEMINFO_SALESTRATEGY_SAVE_BEGIN'
export const SYSTEMINFO_SALESTRATEGY_SAVE_SUCCESS = 'SYSTEMINFO_SALESTRATEGY_SAVE_SUCCESS'
export const SYSTEMINFO_SALESTRATEGY_SAVE_FAILURE = 'SYSTEMINFO_SALESTRATEGY_SAVE_FAILURE'

export const SYSTEMINFO_SALESTRATEGY_DELETE_BEGIN = 'SYSTEMINFO_SALESTRATEGY_DELETE_BEGIN'
export const SYSTEMINFO_SALESTRATEGY_DELETE_SUCCESS = 'SYSTEMINFO_SALESTRATEGY_DELETE_SUCCESS'
export const SYSTEMINFO_SALESTRATEGY_DELETE_FAILURE = 'SYSTEMINFO_SALESTRATEGY_DELETE_FAILURE'

//ReportDesign
export const SYSTEMINFO_REPORTDESIGN_SINGLE_QUERY = 'SYSTEMINFO_REPORTDESIGN_SINGLE_QUERY'
export const SYSTEMINFO_REPORTDESIGN_SINGLE_GOT = 'SYSTEMINFO_REPORTDESIGN_SINGLE_GOT'
export const SYSTEMINFO_REPORTDESIGN_SINGLE_FAILURE = 'SYSTEMINFO_REPORTDESIGN_SINGLE_FAILURE'

export const SYSTEMINFO_REPORTDESIGN_SAVE_BEGIN = 'SYSTEMINFO_REPORTDESIGN_SAVE_BEGIN'
export const SYSTEMINFO_REPORTDESIGN_SAVE_SUCCESS = 'SYSTEMINFO_REPORTDESIGN_SAVE_SUCCESS'
export const SYSTEMINFO_REPORTDESIGN_SAVE_FAILURE = 'SYSTEMINFO_REPORTDESIGN_SAVE_FAILURE'

// BASE DATA ---
// productCategory
export const BASEDATA_PRODUCTCATEGORY_LIST_QUERY = 'BASEDATA_PRODUCTCATEGORY_LIST_QUERY'
export const BASEDATA_PRODUCTCATEGORY_LIST_GOT = 'BASEDATA_PRODUCTCATEGORY_LIST_GOT'
export const BASEDATA_PRODUCTCATEGORY_LIST_FAILURE = 'BASEDATA_PRODUCTCATEGORY_LIST_FAILURE'

export const BASEDATA_PRODUCTCATEGORY_SINGLE_INIT = 'BASEDATA_PRODUCTCATEGORY_SINGLE_INIT'

export const BASEDATA_PRODUCTCATEGORY_SINGLE_QUERY = 'BASEDATA_PRODUCTCATEGORY_SINGLE_QUERY'
export const BASEDATA_PRODUCTCATEGORY_SINGLE_GOT = 'BASEDATA_PRODUCTCATEGORY_SINGLE_GOT'
export const BASEDATA_PRODUCTCATEGORY_SINGLE_FAILURE = 'BASEDATA_PRODUCTCATEGORY_SINGLE_FAILURE'

export const BASEDATA_PRODUCTCATEGORY_SAVE_BEGIN = 'BASEDATA_PRODUCTCATEGORY_SAVE_BEGIN'
export const BASEDATA_PRODUCTCATEGORY_SAVE_SUCCESS = 'BASEDATA_PRODUCTCATEGORY_SAVE_SUCCESS'
export const BASEDATA_PRODUCTCATEGORY_SAVE_FAILURE = 'BASEDATA_PRODUCTCATEGORY_SAVE_FAILURE'


export const BASEDATA_PRODUCTCATEGORY_DELETE_BEGIN = 'BASEDATA_PRODUCTCATEGORY_DELETE_BEGIN'
export const BASEDATA_PRODUCTCATEGORY_DELETE_SUCCESS = 'BASEDATA_PRODUCTCATEGORY_DELETE_SUCCESS'
export const BASEDATA_PRODUCTCATEGORY_DELETE_FAILURE = 'BASEDATA_PRODUCTCATEGORY_DELETE_FAILURE'
// product
export const BASEDATA_PRODUCT_LIST_QUERY = 'BASEDATA_PRODUCT_LIST_QUERY'
export const BASEDATA_PRODUCT_LIST_GOT = 'BASEDATA_PRODUCT_LIST_GOT'
export const BASEDATA_PRODUCT_LIST_FAILURE = 'BASEDATA_PRODUCT_LIST_FAILURE'

export const BASEDATA_PRODUCT_SINGLE_INIT = 'BASEDATA_PRODUCT_SINGLE_INIT'

export const BASEDATA_PRODUCT_SINGLE_QUERY = 'BASEDATA_PRODUCT_SINGLE_QUERY'
export const BASEDATA_PRODUCT_SINGLE_GOT = 'BASEDATA_PRODUCT_SINGLE_GOT'
export const BASEDATA_PRODUCT_SINGLE_FAILURE = 'BASEDATA_PRODUCT_SINGLE_FAILURE'

export const BASEDATA_PRODUCT_SAVE_BEGIN = 'BASEDATA_PRODUCT_SAVE_BEGIN'
export const BASEDATA_PRODUCT_SAVE_SUCCESS = 'BASEDATA_PRODUCT_SAVE_SUCCESS'
export const BASEDATA_PRODUCT_SAVE_FAILURE = 'BASEDATA_PRODUCT_SAVE_FAILURE'


export const BASEDATA_PRODUCT_DELETE_BEGIN = 'BASEDATA_PRODUCT_DELETE_BEGIN'
export const BASEDATA_PRODUCT_DELETE_SUCCESS = 'BASEDATA_PRODUCT_DELETE_SUCCESS'
export const BASEDATA_PRODUCT_DELETE_FAILURE = 'BASEDATA_PRODUCT_DELETE_FAILURE'
// store
export const BASEDATA_STORE_LIST_QUERY = 'BASEDATA_STORE_LIST_QUERY'
export const BASEDATA_STORE_LIST_GOT = 'BASEDATA_STORE_LIST_GOT'
export const BASEDATA_STORE_LIST_FAILURE = 'BASEDATA_STORE_LIST_FAILURE'

export const BASEDATA_STORE_SINGLE_INIT = 'BASEDATA_STORE_SINGLE_INIT'

export const BASEDATA_STORE_SINGLE_QUERY = 'BASEDATA_STORE_SINGLE_QUERY'
export const BASEDATA_STORE_SINGLE_GOT = 'BASEDATA_STORE_SINGLE_GOT'
export const BASEDATA_STORE_SINGLE_FAILURE = 'BASEDATA_STORE_SINGLE_FAILURE'

export const BASEDATA_STORE_SAVE_BEGIN = 'BASEDATA_STORE_SAVE_BEGIN'
export const BASEDATA_STORE_SAVE_SUCCESS = 'BASEDATA_STORE_SAVE_SUCCESS'
export const BASEDATA_STORE_SAVE_FAILURE = 'BASEDATA_STORE_SAVE_FAILURE'


export const BASEDATA_STORE_DELETE_BEGIN = 'BASEDATA_STORE_DELETE_BEGIN'
export const BASEDATA_STORE_DELETE_SUCCESS = 'BASEDATA_STORE_DELETE_SUCCESS'
export const BASEDATA_STORE_DELETE_FAILURE = 'BASEDATA_STORE_DELETE_FAILURE'
// store position
export const BASEDATA_STORE_POSITION_LIST_QUERY = 'BASEDATA_STORE_POSITION_LIST_QUERY'
export const BASEDATA_STORE_POSITION_LIST_GOT = 'BASEDATA_STORE_POSITION_LIST_GOT'
export const BASEDATA_STORE_POSITION_LIST_FAILURE = 'BASEDATA_STORE_POSITION_LIST_FAILURE'

export const BASEDATA_STORE_POSITION_SINGLE_INIT = 'BASEDATA_STORE_POSITION_SINGLE_INIT'

export const BASEDATA_STORE_POSITION_SINGLE_QUERY = 'BASEDATA_STORE_POSITION_SINGLE_QUERY'
export const BASEDATA_STORE_POSITION_SINGLE_GOT = 'BASEDATA_STORE_POSITION_SINGLE_GOT'
export const BASEDATA_STORE_POSITION_SINGLE_FAILURE = 'BASEDATA_STORE_POSITION_SINGLE_FAILURE'

export const BASEDATA_STORE_POSITION_SAVE_BEGIN = 'BASEDATA_STORE_POSITION_SAVE_BEGIN'
export const BASEDATA_STORE_POSITION_SAVE_SUCCESS = 'BASEDATA_STORE_POSITION_SAVE_SUCCESS'
export const BASEDATA_STORE_POSITION_SAVE_FAILURE = 'BASEDATA_STORE_POSITION_SAVE_FAILURE'


export const BASEDATA_STORE_POSITION_DELETE_BEGIN = 'BASEDATA_STORE_POSITION_DELETE_BEGIN'
export const BASEDATA_STORE_POSITION_DELETE_SUCCESS = 'BASEDATA_STORE_POSITION_DELETE_SUCCESS'
export const BASEDATA_STORE_POSITION_DELETE_FAILURE = 'BASEDATA_STORE_POSITION_DELETE_FAILURE'
// supplier
export const BASEDATA_SUPPLIER_LIST_QUERY = 'BASEDATA_SUPPLIER_LIST_QUERY'
export const BASEDATA_SUPPLIER_LIST_GOT = 'BASEDATA_SUPPLIER_LIST_GOT'
export const BASEDATA_SUPPLIER_LIST_FAILURE = 'BASEDATA_SUPPLIER_LIST_FAILURE'

export const BASEDATA_SUPPLIER_SINGLE_INIT = 'BASEDATA_SUPPLIER_SINGLE_INIT'

export const BASEDATA_SUPPLIER_SINGLE_QUERY = 'BASEDATA_SUPPLIER_SINGLE_QUERY'
export const BASEDATA_SUPPLIER_SINGLE_GOT = 'BASEDATA_SUPPLIER_SINGLE_GOT'
export const BASEDATA_SUPPLIER_SINGLE_FAILURE = 'BASEDATA_SUPPLIER_SINGLE_FAILURE'

export const BASEDATA_SUPPLIER_SAVE_BEGIN = 'BASEDATA_SUPPLIER_SAVE_BEGIN'
export const BASEDATA_SUPPLIER_SAVE_SUCCESS = 'BASEDATA_SUPPLIER_SAVE_SUCCESS'
export const BASEDATA_SUPPLIER_SAVE_FAILURE = 'BASEDATA_SUPPLIER_SAVE_FAILURE'


export const BASEDATA_SUPPLIER_DELETE_BEGIN = 'BASEDATA_SUPPLIER_DELETE_BEGIN'
export const BASEDATA_SUPPLIER_DELETE_SUCCESS = 'BASEDATA_SUPPLIER_DELETE_SUCCESS'
export const BASEDATA_SUPPLIER_DELETE_FAILURE = 'BASEDATA_SUPPLIER_DELETE_FAILURE'
// client
export const BASEDATA_CLIENT_LIST_QUERY = 'BASEDATA_CLIENT_LIST_QUERY'
export const BASEDATA_CLIENT_LIST_GOT = 'BASEDATA_CLIENT_LIST_GOT'
export const BASEDATA_CLIENT_LIST_FAILURE = 'BASEDATA_CLIENT_LIST_FAILURE'

export const BASEDATA_CLIENT_SINGLE_INIT = 'BASEDATA_CLIENT_SINGLE_INIT'

export const BASEDATA_CLIENT_SINGLE_QUERY = 'BASEDATA_CLIENT_SINGLE_QUERY'
export const BASEDATA_CLIENT_SINGLE_GOT = 'BASEDATA_CLIENT_SINGLE_GOT'
export const BASEDATA_CLIENT_SINGLE_FAILURE = 'BASEDATA_CLIENT_SINGLE_FAILURE'

export const BASEDATA_CLIENT_SAVE_BEGIN = 'BASEDATA_CLIENT_SAVE_BEGIN'
export const BASEDATA_CLIENT_SAVE_SUCCESS = 'BASEDATA_CLIENT_SAVE_SUCCESS'
export const BASEDATA_CLIENT_SAVE_FAILURE = 'BASEDATA_CLIENT_SAVE_FAILURE'


export const BASEDATA_CLIENT_DELETE_BEGIN = 'BASEDATA_CLIENT_DELETE_BEGIN'
export const BASEDATA_CLIENT_DELETE_SUCCESS = 'BASEDATA_CLIENT_DELETE_SUCCESS'
export const BASEDATA_CLIENT_DELETE_FAILURE = 'BASEDATA_CLIENT_DELETE_FAILURE'
// employee
export const BASEDATA_EMPLOYEE_LIST_QUERY = 'BASEDATA_EMPLOYEE_LIST_QUERY'
export const BASEDATA_EMPLOYEE_LIST_GOT = 'BASEDATA_EMPLOYEE_LIST_GOT'
export const BASEDATA_EMPLOYEE_LIST_FAILURE = 'BASEDATA_EMPLOYEE_LIST_FAILURE'

export const BASEDATA_EMPLOYEE_SINGLE_INIT = 'BASEDATA_EMPLOYEE_SINGLE_INIT'

export const BASEDATA_EMPLOYEE_SINGLE_QUERY = 'BASEDATA_EMPLOYEE_SINGLE_QUERY'
export const BASEDATA_EMPLOYEE_SINGLE_GOT = 'BASEDATA_EMPLOYEE_SINGLE_GOT'
export const BASEDATA_EMPLOYEE_SINGLE_FAILURE = 'BASEDATA_EMPLOYEE_SINGLE_FAILURE'

export const BASEDATA_EMPLOYEE_SAVE_BEGIN = 'BASEDATA_EMPLOYEE_SAVE_BEGIN'
export const BASEDATA_EMPLOYEE_SAVE_SUCCESS = 'BASEDATA_EMPLOYEE_SAVE_SUCCESS'
export const BASEDATA_EMPLOYEE_SAVE_FAILURE = 'BASEDATA_EMPLOYEE_SAVE_FAILURE'


export const BASEDATA_EMPLOYEE_DELETE_BEGIN = 'BASEDATA_EMPLOYEE_DELETE_BEGIN'
export const BASEDATA_EMPLOYEE_DELETE_SUCCESS = 'BASEDATA_EMPLOYEE_DELETE_SUCCESS'
export const BASEDATA_EMPLOYEE_DELETE_FAILURE = 'BASEDATA_EMPLOYEE_DELETE_FAILURE'

// PUCHASE  ---
// purchaseApplication
export const PUCHASE_PURCHASEAPPLICATION_LIST_QUERY = 'PUCHASE_PURCHASEAPPLICATION_LIST_QUERY'
export const PUCHASE_PURCHASEAPPLICATION_LIST_GOT = 'PUCHASE_PURCHASEAPPLICATION_LIST_GOT'
export const PUCHASE_PURCHASEAPPLICATION_LIST_FAILURE = 'PUCHASE_PURCHASEAPPLICATION_LIST_FAILURE'

export const PUCHASE_PURCHASEAPPLICATION_SINGLE_INIT = 'PUCHASE_PURCHASEAPPLICATION_SINGLE_INIT'


export const PUCHASE_PURCHASEAPPLICATION_SINGLE_QUERY = 'PUCHASE_PURCHASEAPPLICATION_SINGLE_QUERY'
export const PUCHASE_PURCHASEAPPLICATION_SINGLE_GOT = 'PUCHASE_PURCHASEAPPLICATION_SINGLE_GOT'
export const PUCHASE_PURCHASEAPPLICATION_SINGLE_FAILURE = 'PUCHASE_PURCHASEAPPLICATION_SINGLE_FAILURE'

export const PUCHASE_PURCHASEAPPLICATION_SAVE_BEGIN = 'PUCHASE_PURCHASEAPPLICATION_SAVE_BEGIN'
export const PUCHASE_PURCHASEAPPLICATION_SAVE_SUCCESS = 'PUCHASE_PURCHASEAPPLICATION_SAVE_SUCCESS'
export const PUCHASE_PURCHASEAPPLICATION_SAVE_FAILURE = 'PUCHASE_PURCHASEAPPLICATION_SAVE_FAILURE'


export const PUCHASE_PURCHASEAPPLICATION_DELETE_BEGIN = 'PUCHASE_PURCHASEAPPLICATION_DELETE_BEGIN'
export const PUCHASE_PURCHASEAPPLICATION_DELETE_SUCCESS = 'PUCHASE_PURCHASEAPPLICATION_DELETE_SUCCESS'
export const PUCHASE_PURCHASEAPPLICATION_DELETE_FAILURE = 'PUCHASE_PURCHASEAPPLICATION_DELETE_FAILURE'

// purchaseAudit
export const PUCHASE_PURCHASEAUDIT_LIST_QUERY = 'PUCHASE_PURCHASEAUDIT_LIST_QUERY'
export const PUCHASE_PURCHASEAUDIT_LIST_GOT = 'PUCHASE_PURCHASEAUDIT_LIST_GOT'
export const PUCHASE_PURCHASEAUDIT_LIST_FAILURE = 'PUCHASE_PURCHASEAUDIT_LIST_FAILURE'

export const PUCHASE_PURCHASEAUDIT_PROCESS_BEGIN = 'PUCHASE_PURCHASEAUDIT_PROCESS_BEGIN'
export const PUCHASE_PURCHASEAUDIT_PROCESS_DONE = 'PUCHASE_PURCHASEAUDIT_PROCESS_DONE'
export const PUCHASE_PURCHASEAUDIT_PROCESS_FAILURE = 'PUCHASE_PURCHASEAUDIT_PROCESS_FAILURE'

// purchaseLoading

export const PUCHASE_PURCHASELOADING_LIST_QUERY = 'PUCHASE_PURCHASELOADING_LIST_QUERY'
export const PUCHASE_PURCHASELOADING_LIST_GOT = 'PUCHASE_PURCHASELOADING_LIST_GOT'
export const PUCHASE_PURCHASELOADING_LIST_FAILURE = 'PUCHASE_PURCHASELOADING_LIST_FAILURE'

export const PUCHASE_PURCHASELOADING_SINGLE_INIT = 'PUCHASE_PURCHASELOADING_SINGLE_INIT'


export const PUCHASE_PURCHASELOADING_SINGLE_QUERY = 'PUCHASE_PURCHASELOADING_SINGLE_QUERY'
export const PUCHASE_PURCHASELOADING_SINGLE_GOT = 'PUCHASE_PURCHASELOADING_SINGLE_GOT'
export const PUCHASE_PURCHASELOADING_SINGLE_FAILURE = 'PUCHASE_PURCHASELOADING_SINGLE_FAILURE'

export const PUCHASE_PURCHASELOADING_SAVE_BEGIN = 'PUCHASE_PURCHASELOADING_SAVE_BEGIN'
export const PUCHASE_PURCHASELOADING_SAVE_SUCCESS = 'PUCHASE_PURCHASELOADING_SAVE_SUCCESS'
export const PUCHASE_PURCHASELOADING_SAVE_FAILURE = 'PUCHASE_PURCHASELOADING_SAVE_FAILURE'


export const PUCHASE_PURCHASELOADING_DELETE_BEGIN = 'PUCHASE_PURCHASELOADING_DELETE_BEGIN'
export const PUCHASE_PURCHASELOADING_DELETE_SUCCESS = 'PUCHASE_PURCHASELOADING_DELETE_SUCCESS'
export const PUCHASE_PURCHASELOADING_DELETE_FAILURE = 'PUCHASE_PURCHASELOADING_DELETE_FAILURE'

// purchaseReturnApplication

export const PUCHASE_PURCHASERETURNAPPLICATION_LIST_QUERY = 'PUCHASE_PURCHASERETURNAPPLICATION_LIST_QUERY'
export const PUCHASE_PURCHASERETURNAPPLICATION_LIST_GOT = 'PUCHASE_PURCHASERETURNAPPLICATION_LIST_GOT'
export const PUCHASE_PURCHASERETURNAPPLICATION_LIST_FAILURE = 'PUCHASE_PURCHASERETURNAPPLICATION_LIST_FAILURE'

export const PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_INIT = 'PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_INIT'


export const PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_QUERY = 'PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_QUERY'
export const PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_GOT = 'PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_GOT'
export const PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_FAILURE = 'PUCHASE_PURCHASERETURNAPPLICATION_SINGLE_FAILURE'

export const PUCHASE_PURCHASERETURNAPPLICATION_SAVE_BEGIN = 'PUCHASE_PURCHASERETURNAPPLICATION_SAVE_BEGIN'
export const PUCHASE_PURCHASERETURNAPPLICATION_SAVE_SUCCESS = 'PUCHASE_PURCHASERETURNAPPLICATION_SAVE_SUCCESS'
export const PUCHASE_PURCHASERETURNAPPLICATION_SAVE_FAILURE = 'PUCHASE_PURCHASERETURNAPPLICATION_SAVE_FAILURE'


export const PUCHASE_PURCHASERETURNAPPLICATION_DELETE_BEGIN = 'PUCHASE_PURCHASERETURNAPPLICATION_DELETE_BEGIN'
export const PUCHASE_PURCHASERETURNAPPLICATION_DELETE_SUCCESS = 'PUCHASE_PURCHASERETURNAPPLICATION_DELETE_SUCCESS'
export const PUCHASE_PURCHASERETURNAPPLICATION_DELETE_FAILURE = 'PUCHASE_PURCHASERETURNAPPLICATION_DELETE_FAILURE'

// purchaseReturnAudit
export const PUCHASE_PURCHASERETURNAUDIT_LIST_QUERY = 'PUCHASE_PURCHASERETURNAUDIT_LIST_QUERY'
export const PUCHASE_PURCHASERETURNAUDIT_LIST_GOT = 'PUCHASE_PURCHASERETURNAUDIT_LIST_GOT'
export const PUCHASE_PURCHASERETURNAUDIT_LIST_FAILURE = 'PUCHASE_PURCHASERETURNAUDIT_LIST_FAILURE'

export const PUCHASE_PURCHASERETURNAUDIT_PROCESS_BEGIN = 'PUCHASE_PURCHASERETURNAUDIT_PROCESS_BEGIN'
export const PUCHASE_PURCHASERETURNAUDIT_PROCESS_DONE = 'PUCHASE_PURCHASERETURNAUDIT_PROCESS_DONE'
export const PUCHASE_PURCHASERETURNAUDIT_PROCESS_FAILURE = 'PUCHASE_PURCHASERETURNAUDIT_PROCESS_FAILURE'

// purchaseReturnApplication

export const PUCHASE_PURCHASERETURN_LIST_QUERY = 'PUCHASE_PURCHASERETURN_LIST_QUERY'
export const PUCHASE_PURCHASERETURN_LIST_GOT = 'PUCHASE_PURCHASERETURN_LIST_GOT'
export const PUCHASE_PURCHASERETURN_LIST_FAILURE = 'PUCHASE_PURCHASERETURN_LIST_FAILURE'

export const PUCHASE_PURCHASERETURN_SINGLE_INIT = 'PUCHASE_PURCHASERETURN_SINGLE_INIT'


export const PUCHASE_PURCHASERETURN_SINGLE_QUERY = 'PUCHASE_PURCHASERETURN_SINGLE_QUERY'
export const PUCHASE_PURCHASERETURN_SINGLE_GOT = 'PUCHASE_PURCHASERETURN_SINGLE_GOT'
export const PUCHASE_PURCHASERETURN_SINGLE_FAILURE = 'PUCHASE_PURCHASERETURN_SINGLE_FAILURE'

export const PUCHASE_PURCHASERETURN_SAVE_BEGIN = 'PUCHASE_PURCHASERETURN_SAVE_BEGIN'
export const PUCHASE_PURCHASERETURN_SAVE_SUCCESS = 'PUCHASE_PURCHASERETURN_SAVE_SUCCESS'
export const PUCHASE_PURCHASERETURN_SAVE_FAILURE = 'PUCHASE_PURCHASERETURN_SAVE_FAILURE'


export const PUCHASE_PURCHASERETURN_DELETE_BEGIN = 'PUCHASE_PURCHASERETURN_DELETE_BEGIN'
export const PUCHASE_PURCHASERETURN_DELETE_SUCCESS = 'PUCHASE_PURCHASERETURN_DELETE_SUCCESS'
export const PUCHASE_PURCHASERETURN_DELETE_FAILURE = 'PUCHASE_PURCHASERETURN_DELETE_FAILURE'


// PurchaseFiled
export const PUCHASE_PURCHASEFILED_LIST_QUERY = 'PUCHASE_PURCHASEFILED_LIST_QUERY'
export const PUCHASE_PURCHASEFILED_LIST_GOT = 'PUCHASE_PURCHASEFILED_LIST_GOT'
export const PUCHASE_PURCHASEFILED_LIST_FAILURE = 'PUCHASE_PURCHASEFILED_LIST_FAILURE'

export const PUCHASE_PURCHASEFILED_DETAIL_BEGIN = 'PUCHASE_PURCHASEFILED_DETAIL_BEGIN'
export const PUCHASE_PURCHASEFILED_DETAIL_DONE = 'PUCHASE_PURCHASEFILED_DETAIL_DONE'
export const PUCHASE_PURCHASEFILED_DETAIL_FAILURE = 'PUCHASE_PURCHASEFILED_DETAIL_FAILURE'
