// location change
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

// header 部分的快捷方式
export const SHORTCUT_INITING = 'SHORTCUT_INITING'
export const SHORTCUT_INITED = 'SHORTCUT_INITED'
export const SHORTCUT_FAILURE = 'SHORTCUT_FAILURE'

// header 部分的用户信息获取方式
export const LOGIN_INFO_INITING = 'LOGIN_INFO_INITING'
export const LOGIN_INFO_INITED = 'LOGIN_INFO_INITED'
export const LOGIN_INFO_FAILURE = 'LOGIN_INFO_FAILURE'


// leftMenu 可用目录获取
export const LEFT_MENU_INITING = 'LEFT_MENU_INITING'
export const LEFT_MENU_INITED = 'LEFT_MENU_INITED'
export const LEFT_MENU_FAILURE = 'LEFT_MENU_FAILURE'


// 首页数据获取
export const INDEX_DATA_INITING = 'INDEX_DATA_INITING'
export const INDEX_DATA_INITED = 'INDEX_DATA_INITED'
export const INDEX_DATA_FAILURE = 'INDEX_DATA_FAILURE'

// 访问控制 ---
// 职位管理 ---
export const ACCESSCONTROL_POST_LIST_QUERY = 'ACCESSCONTROL_POST_LIST_QUERY'
export const ACCESSCONTROL_POST_LIST_GOT = 'ACCESSCONTROL_POST_LIST_GOT'
export const ACCESSCONTROL_POST_LIST_FAILURE = 'ACCESSCONTROL_POST_LIST_FAILURE'

export const ACCESSCONTROL_POST_SINGLE_INIT = 'ACCESSCONTROL_POST_SINGLE_INIT'

export const ACCESSCONTROL_POST_SINGLE_QUERY = 'ACCESSCONTROL_POST_SINGLE_QUERY'
export const ACCESSCONTROL_POST_SINGLE_GOT = 'ACCESSCONTROL_POST_SINGLE_GOT'
export const ACCESSCONTROL_POST_SINGLE_FAILURE = 'ACCESSCONTROL_POST_SINGLE_FAILURE'

export const ACCESSCONTROL_POST_SAVE_BEGIN = 'ACCESSCONTROL_POST_SAVE_BEGIN'
export const ACCESSCONTROL_POST_SAVE_SUCCESS = 'ACCESSCONTROL_POST_SAVE_SUCCESS'
export const ACCESSCONTROL_POST_SAVE_FAILURE = 'ACCESSCONTROL_POST_SAVE_FAILURE'
