export const INIT_FIRST_PAGE = 'INIT_FIRST_PAGE'
export const INIT_COMMITTED_1 = 'INIT_COMMITTED_1'
export const INIT_COMMITTED_2 = 'INIT_COMMITTED_2'
export const INIT_COMMITTED_3 = 'INIT_COMMITTED_3'
